layout_spectrum: 0.36351722047682666
typography_spectrum: 0.7947565944017935
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.9736030515525859
  lightness: 0.49604147493774714
  saturation: 0.768999945137115
  rhythmicContrast: 0.13460744703345295
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
author:
  name: ''
  url: ''
  email: ''
name: Beer Gallery
navigation:
  - name: 'An undisputed Queen: Her crown shines bold and ever bright.'
    id: 68db58fe-e0ba-4918-8a79-a1166956d0ae
    type: content
  - name: A punchy number and a lady of few words…
    id: 5077065b-ffe5-4d30-8f5f-64899dcd6d14
    type: content
  - name: Beer and sunshine need each other like a tap needs it's barrel.
    id: ae95c24f-adc5-4a05-b48b-284228d44f6a
    type: content
  - name: 'Lokalbier & El Lokal: a true location beer'
    id: 70953e48-0246-423f-8b9a-520ada0e5eba
    type: content
title: 'Thirst appreciation. Satisfaction, guaranteed.'
content: []
description: Hipster beer pictures
