name: Beer Gallery
layout_spectrum: 0.6592740627610096
typography_spectrum: 0.2605386013968626
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.0884055624931177
  lightness: 0.21488076341201867
  saturation: 0.6583981762472831
  rhythmicContrast: 0.8328962934230106
title: 'Thirst appreciation. Hipster satisfaction, guaranteed. '
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
