layout_spectrum: 0.7834087877999991
typography_spectrum: 0.40393707854673266
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.276704094838351
  lightness: 0.1627317580860108
  saturation: 0.9127963967621326
  rhythmicContrast: 0.7570043015293777
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
author:
  name: ''
  url: ''
  email: ''
name: Beer Gallery
title: 'Thirst appreciation. Satisfaction, guaranteed.'
